name: build-and-test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: CI - Build/Test on develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --verbosity normal -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport

      # Build docker containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image - API
        run: |
          docker build -t gotorz-api-test -f src/GoTorz.API/Dockerfile src/GoTorz.API

      - name: Build Docker image - Client
        run: |
          docker build -t gotorz-client-test -f src/GoTorz.Client/Dockerfile src/GoTorz.Client


# We push manually because our Azure Student Accounts do not have access to app registrations which is needed to make github push images automatically
# cd:
 #  if: github.ref == 'refs/heads/main'
  # runs-on: ubuntu-latest
   # name: CD - (disabled) Manual Docker Push instead
     # steps:
      # - name: Checkout code
      #  uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to Azure
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Log in to ACR
      #   run: az acr login --name gotorzacr

      # - name: Build and push API image
      #   run: |
      #     docker build -t gotorzacr.azurecr.io/gotorz-api:latest -f GoTorz.API/Dockerfile .
      #     docker push gotorzacr.azurecr.io/gotorz-api:latest

      # - name: Build and push Client image
      #   run: |
      #     docker build -t gotorzacr.azurecr.io/gotorz-client:latest -f GoTorz.Client/Dockerfile .
      #     docker push gotorzacr.azurecr.io/gotorz-client:latest


